### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by PhanaticD** [plushmonkey/JedCore#45]
first issue: 
```
[16:41:23 WARN]: java.lang.NullPointerException
[16:41:23 WARN]:        at com.jedk1.jedcore.collision.AABB.min(AABB.java:176)
[16:41:23 WARN]:        at com.jedk1.jedcore.collision.AABB.<init>(AABB.java:51)
[16:41:23 WARN]:        at com.jedk1.jedcore.collision.CollisionDetector.checkEntityCollisions(CollisionDetector.java:51)
[16:41:23 WARN]:        at com.jedk1.jedcore.collision.CollisionDetector.checkEntityCollisions(CollisionDetector.java:19)
[16:41:23 WARN]:        at com.jedk1.jedcore.ability.airbending.AirPunch.progressShots(AirPunch.java:122)
[16:41:23 WARN]:        at com.jedk1.jedcore.ability.airbending.AirPunch.progress(AirPunch.java:67)
[16:41:23 WARN]:        at com.projectkorra.projectkorra.ability.CoreAbility.progressAll(CoreAbility.java:254)
[16:41:23 WARN]:        at com.projectkorra.projectkorra.BendingManager.run(BendingManager.java:116)
[16:41:23 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:41:23 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[16:41:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1111)
[16:41:23 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[16:41:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057)
[16:41:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902)
[16:41:23 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PhanaticD** [comment]
```
                try {
                    getVoxelShape = Block.getDeclaredMethod("a", IBlockData, IBlockAccess, BlockPosition);
                } catch (NoSuchMethodException e) {
                    getVoxelShape = Block.getDeclaredMethod("i", IBlockData, IBlockAccess, BlockPosition);
                }
```
adding this seems to have fixed it

**Comment by arriansamsul** [comment]
where do i put this code?

**Comment by dkoraq** [comment]
> where do i put this code?

+
