### ISSUE TITLE
Crazy infinite errors on load

### ISSUE THREAD

**Issue by HappyHippo77** [plushmonkey/JedCore#46]
So when I try to load my server I get one error which repeats itself many times and then one which endlessly loops and the server never finishes loading.
This is the repeated error:
```
[09:56:56 ERROR]: Could not pass event BlockFromToEvent to JedCore v2.8.1-Spigot1.13.2-PK1.8.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:191) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:163) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:485) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.Fluid.a(SourceFile:56) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:630) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:77) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:622) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:278) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:885) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:791) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:694) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com.projectkorra.projectkorra.ability.ElementalAbility
        at com.jedk1.jedcore.listener.JCListener.onFlow(JCListener.java:108) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        ... 16 more
```

This is the infinite loop:
`[09:57:25 WARN]: [JedCore] Task #8 for JedCore v2.8.1-Spigot1.13.2-PK1.8.8 generated an exception
java.lang.NoClassDefFoundError: com.projectkorra.projectkorra.ability.ElementalAbility
        at com.jedk1.jedcore.JCManager.run(JCManager.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:390) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:832) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:791) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:694) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

**Comment by plushmonkey** [comment]
Both ProjectKorra and JedCore require Spigot or Paper, not CraftBukkit. If you're not using CraftBukkit, the error is happening here because either ProjectKorra isn't loading or you're using a custom ProjectKorra build with a different api.

**Comment by HappyHippo77** [comment]
Oh I see. I thought bukkit and spigot were cross compatible for some odd reason >.<'
