### ISSUE TITLE
PlayerAnimationEvent

### ISSUE THREAD

**Issue by albrechet** [plushmonkey/JedCore#47]
Hey, I read the other posts about this and they all seemed unanswered but closed. Was wondering what the error meant and if there is a fix for it.

[05:03:30] [Server thread/ERROR]: Could not pass event PlayerAnimationEvent to JedCore v2.7.2-Spigot1.12.2-PK1.8.7org.bukkit.event.EventException: nullat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1663) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:32) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.PacketPlayInArmAnimation.a(SourceFile:9) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$1970.00000000840E0A10.run(Unknown Source) ~[?:?]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.NoClassDefFoundError: com.projectkorra.projectkorra.util.ParticleEffect$ParticleDataat com.jedk1.jedcore.listener.AbilityListener.onPlayerSwing(AbilityListener.java:163) ~[?:?]at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]... 16 moreCaused by: java.lang.ClassNotFoundException: com.projectkorra.projectkorra.util.ParticleEffect$ParticleDataat java.net.URLClassLoader.findClass(URLClassLoader.java:592) ~[?:1.8.0_192]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:934) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:879) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:862) ~[?:1.8.0_192]at com.jedk1.jedcore.listener.AbilityListener.onPlayerSwing(AbilityListener.java:163) ~[?:?]at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1a3504a-a46fdbc]

**Comment by plushmonkey** [comment]
It looks like you're mixing versions. If you're using Spigot 1.13.2 then you want to be running ProjectKorra 1.8.8 and JedCore 2.8.1.

You can find the latest JedCore [here](https://github.com/plushmonkey/JedCore/releases/tag/2.8.1).
