### ISSUE TITLE
Firepunch not working 

### ISSUE THREAD

**Issue by Pickle9775** [plushmonkey/JedCore#50]
The move FirePunch is supposed to set the target mob on fire as well as deal some damage, instead it doe nothing but produce flame particles from the user's hand. Here is the error message from the server console. 

`[00:43:07] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to JedCore v2.9.4-Spigot1.15-PK1.8.9
java.lang.IncompatibleClassChangeError: Expected static method com.jedk1.jedcore.ability.firebending.FirePunch.playFirebendingParticles(Lorg/bukkit/Location;IDDD)V
	at com.jedk1.jedcore.ability.firebending.FirePunch.punch(FirePunch.java:65) ~[?:?]
	at com.jedk1.jedcore.listener.JCListener.onEntityDamageByEntity(JCListener.java:142) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-91]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:246) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1034) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:921) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:877) ~[patched_1.16.1.jar:git-Paper-91]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1066) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1826) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1092) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1861) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2135) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-91]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-91]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]``

**Comment by Pickle9775** [comment]
Never mind, I am just a fool and used the wrong version of PK with this version of Jedcore. Hopefully this will not be an issue in the next release.
